In [2]:
print(cv2.__version__)

4.2.0


In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from random import randrange

In [5]:
img = cv2.imread('C:/Users/Admin/Desktop/project/stitch/right.png')
img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img1 = cv2.imread('C:/Users/Admin/Desktop/project/stitch/left.png')
img1 = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)

sift = cv2.xfeatures2d.SIFT_create()
# find the keypoints and descriptors with SIFT
kp1, des1 = sift.detectAndCompute(img,None)
kp2, des2 = sift.detectAndCompute(img1,None)

bf = cv2.BFMatcher()
matches = bf.knnMatch(des1,des2, k=2)

# Apply ratio test
good = []
for m in matches:
    if m[0].distance < 0.5*m[1].distance:
        good.append(m)
matches = np.asarray(good)


if len(matches[:,0]) >= 4:
    src = np.float32([ kp1[m.queryIdx].pt for m in matches[:,0] ]).reshape(-1,1,2)
    dst = np.float32([ kp2[m.trainIdx].pt for m in matches[:,0] ]).reshape(-1,1,2)

    H, masked = cv2.findHomography(src, dst, cv2.RANSAC, 5.0)
    print (H)
else:
    raise AssertionError("Can't find enough keypoints.")

dst = cv2.warpPerspective(img1,H,(img.shape[1] + img1.shape[1], img.shape[0]))

dst[0:img.shape[0], 0:img.shape[1]] = img
cv2.imshow('output.jpg',dst)

cv2.waitKey(0)  
  
#closing all open windows  
cv2.destroyAllWindows()  

[[ 7.65715731e-01  3.72082574e-02  4.46807943e+02]
 [-1.35565541e-01  9.12377362e-01  7.60569812e+01]
 [-2.10834981e-04 -3.20176690e-05  1.00000000e+00]]


In [4]:
img = cv2.imread('C:/Users/Admin/Desktop/project/stitch/right.png')
cv2.imshow('img',img)
cv2.waitKey(0)  
  
#closing all open windows  
cv2.destroyAllWindows()  

In [9]:
import cv2

imageFiles = ['test1.png','test2.png']
images = []
for filename in imageFiles:
    img = cv2.imread(filename)
    images.append(img)

cv2.ocl.setUseOpenCL(False)
stitcher = cv2.Stitcher.create()
status, result = stitcher.stitch(images)             
cv2.imwrite('result.png',result)
cv2.waitKey(0)  
  
#closing all open windows  
cv2.destroyAllWindows()  

[array([[[106, 105, 104],
        [128, 128, 128],
        [ 79,  87,  86],
        ...,
        [106, 105, 104],
        [237, 234, 231],
        [237, 234, 231]],

       [[106, 105, 104],
        [128, 128, 128],
        [  0,   0,   0],
        ...,
        [106, 105, 104],
        [237, 234, 231],
        [237, 234, 231]],

       [[112, 112, 112],
        [128, 128, 128],
        [  0,   0,   0],
        ...,
        [112, 112, 112],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[106, 106, 106],
        [128, 128, 128],
        [128, 128, 128],
        ...,
        [109, 109, 109],
        [247, 247, 247],
        [247, 247, 247]],

       [[106, 106, 106],
        [106, 106, 106],
        [106, 106, 106],
        ...,
        [109, 109, 109],
        [247, 247, 247],
        [247, 247, 247]],

       [[238, 238, 238],
        [238, 238, 238],
        [238, 238, 238],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
